-- AlterTable
ALTER TABLE `khachhang` ADD COLUMN `DiaChi` VARCHAR(255) NULL;

-- AlterTable
ALTER TABLE `sach` ADD COLUMN `HinhAnh` LONGTEXT NULL,
    ADD COLUMN `KichThuoc` VARCHAR(50) NULL,
    ADD COLUMN `NamXuatBan` INTEGER NULL,
    ADD COLUMN `SoTrang` INTEGER NULL,
    ADD COLUMN `TonKhoToiThieu` INTEGER NULL DEFAULT 10,
    ADD COLUMN `TrongLuong` INTEGER NULL;
